const products = [
  {
    name: "Manzana",
    id: 1,
    image: "manzana.png",
    pricePound: 3000,
    category: "frutas",
    from: "Rionegro",
    description: "Tampoco tiene potaxio",
  },
  {
    name: "Sandía",
    id: 2,
    image: "sandia.png",
    pricePound: 10000,
    category: "frutas",
    from: "El Retiro",
    description: "No tiene potaxio",
  },
  {
    name: "Fresa",
    id: 3,
    image: "fresa.png",
    pricePound: 5200,
    category: "frutas",
    from: "Rionegro",
    description: "Tampoco tiene potaxio",
  },
  {
    name: "Banano",
    id: 4,
    image: "banano.png",
    pricePound: 150000,
    category: "frutas",
    from: "Barbosa",
    description: "Tiene potaxio",
  },
  {
    name: "Cereza",
    id: 5,
    image: "cereza.png",
    pricePound: 150000,
    category: "frutas",
    from: "Barbosa",
    description: "No tiene potaxio",
  },
  {
    name: "Melón",
    id: 6,
    image: "melon.png",
    pricePound: 150000,
    category: "frutas",
    from: "Barbosa",
    description: "No tiene potaxio",
  },
  {
    name: "Mango",
    id: 7,
    image: "mango.png",
    pricePound: 150000,
    category: "frutas",
    from: "Barbosa",
    description: "No tiene potaxio",
  },
  {
    name: "Pera",
    id: 8,
    image: "pera.png",
    pricePound: 150000,
    category: "frutas",
    from: "Barbosa",
    description: "No tiene potaxio",
  },
];
